### ISSUE TITLE
Use github's API to have a commit ticker at the footer

### ISSUE THREAD

**Issue by torch2424** [torch2424/PersonalSite#19]
inspired by @dauidus

on his website
http://www.dauid.us/

**Comment by dauidus** [comment]
https://gist.github.com/dauidus/8c72e70b569afa9ba223

You'll need to mess around with it a bit, but it'll get you going.  :-)

**Comment by torch2424** [comment]
@dauidus Thank you! :)

**Comment by torch2424** [comment]
Decided against this, as I have links to my github all over the site, and I want to keep it minimal. Also, I can't think of a good place for it among my current layout

**Comment by dauidus** [comment]
No worries!  My plugin needs a little work, anyways - I haven't updated it to be compatible with github's activity icons.

**Comment by torch2424** [comment]
Oh! It;s not your plugins fault at all, it's more of my own. My footer is already kind of crowded, and I didn't want to shove anything else down there. But I do appreciate you sharing the plugin code with me! :)
